name: relight
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.8.2
  custom_lint: ^0.4.0
  dio: ^5.3.2
  equatable: ^2.0.3
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_messaging: ^14.2.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  go_router: ^12.1.1
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  iconly: ^1.0.1
  intl: ^0.18.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  pretty_dio_logger: ^1.3.1
  sign_in_with_apple: ^5.0.0

dev_dependencies:
  build_runner: ^2.4.5
  fake_cloud_firestore: ^2.4.1+1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  riverpod_lint: ^1.3.2
  mocktail: ^1.0.1
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
