name: relight
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  cloud_firestore: ^4.8.2
  custom_lint: ^0.5.7
  device_info_plus: ^9.1.1
  dio: ^5.3.2
  equatable: ^2.0.5
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_messaging: ^14.2.2
  flash: ^3.0.5+2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^9.2.2
  flutter_riverpod: ^2.3.6
  flutter_timezone: ^1.0.8
  gap: ^3.0.1
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.4
  iconly: ^1.0.1
  intl: ^0.18.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  pretty_dio_logger: ^1.3.1
  quill_html_converter: ^9.2.2
  sign_in_with_apple: ^5.0.0
  super_clipboard: ^0.8.2+1
  url_launcher: ^6.2.4

dev_dependencies:
  build_runner: ^2.4.5
  fake_cloud_firestore: ^2.4.1+1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  json_serializable: ^6.7.0
  riverpod_lint: ^2.3.7
  mocktail: ^1.0.1
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
