// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd0tTbSjPSh2PczV0ccEmbQPuKIeDzxO0',
    appId: '1:161901170853:web:7a7f5b1e86f5c021b5fd4c',
    messagingSenderId: '161901170853',
    projectId: 'relight-bdd93',
    authDomain: 'relight-bdd93.firebaseapp.com',
    storageBucket: 'relight-bdd93.appspot.com',
    measurementId: 'G-3VGR2M4DHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX9vT8EQ5DffkKLcKXSBd80y1zDk372Tk',
    appId: '1:161901170853:android:7898e54d757bd867b5fd4c',
    messagingSenderId: '161901170853',
    projectId: 'relight-bdd93',
    storageBucket: 'relight-bdd93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlQot3aFwlGWFU5s6zMA8-39mn06Raw68',
    appId: '1:161901170853:ios:a5d7c1e0c154e5f0b5fd4c',
    messagingSenderId: '161901170853',
    projectId: 'relight-bdd93',
    storageBucket: 'relight-bdd93.appspot.com',
    iosClientId:
        '161901170853-0k0m6bsb6dcme0d4i7ms4lv8umjpo0rc.apps.googleusercontent.com',
    iosBundleId: 'com.relight.app',
  );
}
